/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    brands: Brand;
    blogs: Blog;
    categories: Category;
    'legal-pages': LegalPage;
    'listing-pages': ListingPage;
    pages: Page;
    products: Product;
    customers: Customer;
    'customer-identities': CustomerIdentity;
    'promo-codes': PromoCode;
    carts: Cart;
    orders: Order;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    'listing-pages': ListingPagesSelect<false> | ListingPagesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'customer-identities': CustomerIdentitiesSelect<false> | CustomerIdentitiesSelect<true>;
    'promo-codes': PromoCodesSelect<false> | PromoCodesSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'home-page': HomePage;
    'blog-page': BlogPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  shortDescription?: string | null;
  story?: string | null;
  /**
   * Flexible brand detail page sections.
   */
  layout?:
    | (
        | {
            section: {
              title: string;
              browseLabel: string;
              browseType: 'internal' | 'external';
              browseOpenInNewTab?: boolean | null;
              /**
               * Select an internal page.
               */
              browseReference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'legal-pages';
                    value: number | LegalPage;
                  } | null)
                | ({
                    relationTo: 'listing-pages';
                    value: number | ListingPage;
                  } | null)
                | ({
                    relationTo: 'products';
                    value: number | Product;
                  } | null)
                | ({
                    relationTo: 'categories';
                    value: number | Category;
                  } | null);
              /**
               * Optional section ID, without the # symbol.
               */
              browseAnchor?: string | null;
              /**
               * Enter a full URL or relative path.
               */
              browseUrl?: string | null;
            };
            visual?: {
              image?: (number | null) | Media;
              copy?: string | null;
            };
            /**
             * Select the products shown in this brand slider.
             */
            products: (number | Product)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'brand-product-slider';
          }
        | {
            section: {
              /**
               * Heading shown above the brand tiles.
               */
              title: string;
              browseLabel: string;
              browseType: 'internal' | 'external';
              browseOpenInNewTab?: boolean | null;
              /**
               * Select an internal page.
               */
              browseReference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'legal-pages';
                    value: number | LegalPage;
                  } | null)
                | ({
                    relationTo: 'listing-pages';
                    value: number | ListingPage;
                  } | null)
                | ({
                    relationTo: 'products';
                    value: number | Product;
                  } | null)
                | ({
                    relationTo: 'categories';
                    value: number | Category;
                  } | null);
              /**
               * Optional section ID, without the # symbol.
               */
              browseAnchor?: string | null;
              /**
               * Enter a full URL or relative path.
               */
              browseUrl?: string | null;
            };
            tiles?:
              | {
                  label: string;
                  backgroundImage: number | Media;
                  cardType: 'internal' | 'external';
                  cardOpenInNewTab?: boolean | null;
                  /**
                   * Select an internal page.
                   */
                  cardReference?:
                    | ({
                        relationTo: 'pages';
                        value: number | Page;
                      } | null)
                    | ({
                        relationTo: 'legal-pages';
                        value: number | LegalPage;
                      } | null)
                    | ({
                        relationTo: 'listing-pages';
                        value: number | ListingPage;
                      } | null)
                    | ({
                        relationTo: 'products';
                        value: number | Product;
                      } | null)
                    | ({
                        relationTo: 'categories';
                        value: number | Category;
                      } | null);
                  /**
                   * Optional section ID, without the # symbol.
                   */
                  cardAnchor?: string | null;
                  /**
                   * Enter a full URL or relative path.
                   */
                  cardUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'brand-tile-grid';
          }
        | {
            title: string;
            subtitle: string;
            image?: (number | null) | Media;
            actionLabel?: string | null;
            actionType: 'internal' | 'external';
            actionOpenInNewTab?: boolean | null;
            /**
             * Select an internal page.
             */
            actionReference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'legal-pages';
                  value: number | LegalPage;
                } | null)
              | ({
                  relationTo: 'listing-pages';
                  value: number | ListingPage;
                } | null)
              | ({
                  relationTo: 'products';
                  value: number | Product;
                } | null)
              | ({
                  relationTo: 'categories';
                  value: number | Category;
                } | null);
            /**
             * Optional section ID, without the # symbol.
             */
            actionAnchor?: string | null;
            /**
             * Enter a full URL or relative path.
             */
            actionUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'brand-cta-banner';
          }
      )[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  title: string;
  sections: {
    title: string;
    content: string;
    id?: string | null;
    blockName?: string | null;
    blockType: 'content-section';
  }[];
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-pages".
 */
export interface ListingPage {
  id: number;
  title: string;
  description?: string | null;
  preappliedBrands?: (number | Brand)[] | null;
  preappliedCategories?: (number | Category)[] | null;
  /**
   * Use when the page should be locked to one or more product types.
   */
  preappliedProductTypes?:
    | (
        | 'single_serve_beverage'
        | 'packaged_coffee'
        | 'equipment'
        | 'accessory'
        | 'drink_mix_ingredient'
        | 'technical_consumable'
        | 'tea_matcha'
        | 'cold_beverage_concentrate'
        | 'confectionery_snack'
      )[]
    | null;
  /**
   * Choose which catalog filters editors want to expose on this page. Locked filters stay active in the background.
   */
  visibleFilterKeys?: ('brand' | 'categoryName' | 'format' | 'priceValue')[] | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  description?: string | null;
  image?: (number | null) | Media;
  parent?: (number | null) | Category;
  /**
   * Leave empty to allow this category across all product types.
   */
  allowedProductTypes?:
    | (
        | 'single_serve_beverage'
        | 'packaged_coffee'
        | 'equipment'
        | 'accessory'
        | 'drink_mix_ingredient'
        | 'technical_consumable'
        | 'tea_matcha'
        | 'cold_beverage_concentrate'
        | 'confectionery_snack'
      )[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  categories: (number | Category)[];
  badges?: ('new' | 'best-seller' | 'limited' | 'sale')[] | null;
  heroImage: number | Media;
  /**
   * Short customer-facing descriptors rendered as PDP pills.
   */
  notes?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  /**
   * Customer-facing PDP table rows. These do not drive filters.
   */
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  relatedProducts?: (number | Product)[] | null;
  singleServeDetails?: {
    format?: ('capsules' | 'pods') | null;
    beverageType?: ('coffee' | 'milk' | 'tea') | null;
    compatibleSystems?:
      | ('ese_44_mm' | 'lavazza_a_modo_mio' | 'lavazza_blue' | 'lavazza_espresso_point' | 'tchibo_cafissimo')[]
      | null;
    packageUnits?: number | null;
    netContent?: {
      generateDisplay?: boolean | null;
      amount?: number | null;
      unit?: ('g' | 'kg' | 'ml' | 'l' | 'kom') | null;
      display?: string | null;
    };
    flags?: 'decaf'[] | null;
  };
  packagedCoffeeDetails?: {
    format?: ('beans' | 'ground') | null;
    packageUnits?: number | null;
    netContent?: {
      generateDisplay?: boolean | null;
      amount?: number | null;
      unit?: ('g' | 'kg' | 'ml' | 'l' | 'kom') | null;
      display?: string | null;
    };
    flags?: ('decaf' | 'organic')[] | null;
  };
  equipmentDetails?: {
    equipmentType?:
      | (
          | 'bean_to_cup_machine'
          | 'capsule_machine'
          | 'cold_water_dispenser'
          | 'espresso_machine'
          | 'filter_machine'
          | 'grinder'
          | 'hot_drinks_machine'
          | 'instant_coffee_machine'
          | 'milk_fridge'
          | 'vending_machine'
        )
      | null;
    compatibleSystems?: ('animo_optime' | 'lavazza_blue')[] | null;
    waterConnection?: ('direct_plumb' | 'manual_fill' | 'tank_or_direct_plumb') | null;
    burrType?: ('conical' | 'flat') | null;
    powerW?: number | null;
    ratedPowerW?: number | null;
    waterTankL?: number | null;
    groupCount?: number | null;
    burrDiameterMm?: number | null;
    ingredientCanistersCount?: number | null;
    directSelections?: number | null;
    hourCapacityL?: number | null;
  };
  accessoryDetails?: {
    compatibleSystems?: 'animo_optime'[] | null;
    packageUnits?: number | null;
    powerW?: number | null;
  };
  drinkMixDetails?: {
    format?: ('powder' | 'sachets' | 'syrup') | null;
    beverageType?:
      | (
          | 'chai_latte'
          | 'coffee'
          | 'ginseng'
          | 'hot_chocolate'
          | 'matcha_latte'
          | 'milk'
          | 'pumpkin_spice_latte'
          | 'white_chocolate'
        )
      | null;
    physicalForm?: ('powder' | 'sachets' | 'sticks' | 'syrup') | null;
    coffeeForm?: 'instant' | null;
    flavour?: ('hazelnut' | 'salted_caramel' | 'vanilla') | null;
    packageUnits?: number | null;
    netContent?: {
      generateDisplay?: boolean | null;
      amount?: number | null;
      unit?: ('g' | 'kg' | 'ml' | 'l' | 'kom') | null;
      display?: string | null;
    };
    flags?: 'decaf'[] | null;
  };
  technicalConsumableDetails?: {
    physicalForm?: 'cartridge' | null;
    compatibleSystems?:
      | (
          | 'coffee_machines'
          | 'combi_steamers'
          | 'espresso_machines'
          | 'horeca_beverage_equipment'
          | 'ovens'
          | 'vending_machines'
        )[]
      | null;
    flags?: 'organic'[] | null;
  };
  teaMatchaDetails?: {
    teaType?: ('black' | 'chai' | 'fruit_infusion' | 'green' | 'herbal' | 'rooibos') | null;
    flavorFamily?: 'apple_pear' | null;
    packageUnits?: number | null;
    netContent?: {
      generateDisplay?: boolean | null;
      amount?: number | null;
      unit?: ('g' | 'kg' | 'ml' | 'l' | 'kom') | null;
      display?: string | null;
    };
    flags?: 'organic'[] | null;
  };
  coldBeverageDetails?: {
    beverageType?: 'juice_concentrate' | null;
    flavour?: 'apple' | null;
    packageUnits?: number | null;
    netContent?: {
      generateDisplay?: boolean | null;
      amount?: number | null;
      unit?: ('g' | 'kg' | 'ml' | 'l' | 'kom') | null;
      display?: string | null;
    };
  };
  confectioneryDetails?: {
    productForm?: ('bar' | 'marshmallows') | null;
    packageUnits?: number | null;
    netContent?: {
      generateDisplay?: boolean | null;
      amount?: number | null;
      unit?: ('g' | 'kg' | 'ml' | 'l' | 'kom') | null;
      display?: string | null;
    };
    flags?: 'decaf'[] | null;
  };
  moralis: {
    /**
     * Internal Moralis reference mapped to SIF_ART.
     */
    itemID: string;
    /**
     * Synced from Moralis and shown here for reference only.
     */
    sku?: string | null;
    price?: number | null;
    stockQuantity?: number | null;
    availabilityStatus?: ('available' | 'unavailable') | null;
    isAvailable?: boolean | null;
    barcode?: string | null;
    unit?: string | null;
    taxRate?: number | null;
    lastSyncStatus?: ('never-synced' | 'succeeded' | 'failed') | null;
    lastSyncedAt?: string | null;
    lastSyncError?: string | null;
    rawOperationalData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  status: 'draft' | 'active' | 'archived';
  productType:
    | 'single_serve_beverage'
    | 'packaged_coffee'
    | 'equipment'
    | 'accessory'
    | 'drink_mix_ingredient'
    | 'technical_consumable'
    | 'tea_matcha'
    | 'cold_beverage_concentrate'
    | 'confectionery_snack';
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Review-required products should use raw Moralis fallback content instead of enriched product facts.
   */
  catalogReviewStatus: 'ready' | 'review_required' | 'do_not_publish';
  brand?: (number | null) | Brand;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  category: string;
  publishedAt: string;
  readingTime: string;
  excerpt: string;
  heroBadges: {
    primaryLabel: string;
    stampLabel: string;
  };
  image: number | Media;
  /**
   * Flexible blog detail page blocks shown below the intro.
   */
  layout: (
    | {
        content: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'callout-block';
      }
    | {
        title: string;
        image?: (number | null) | Media;
        caption?: string | null;
        content: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'content-block';
      }
  )[];
  relatedBlogs: {
    /**
     * Heading shown above the related blogs section on this blog detail page.
     */
    eyebrow?: string | null;
    title: string;
    /**
     * Choose the blogs shown in the related blogs section on this blog detail page.
     */
    blogs?: (number | Blog)[] | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  firstName: string;
  lastName: string;
  phone?: string | null;
  billingAddress?: {
    firstName?: string | null;
    lastName?: string | null;
    isBusiness?: boolean | null;
    company?: string | null;
    taxId?: string | null;
    phone?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    postalCode?: string | null;
    region?: string | null;
    country?: string | null;
  };
  shippingAddress?: {
    firstName?: string | null;
    lastName?: string | null;
    isBusiness?: boolean | null;
    company?: string | null;
    taxId?: string | null;
    phone?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    postalCode?: string | null;
    region?: string | null;
    country?: string | null;
  };
  savedAddresses?:
    | {
        isDefault?: boolean | null;
        firstName?: string | null;
        lastName?: string | null;
        isBusiness?: boolean | null;
        company?: string | null;
        taxId?: string | null;
        phone?: string | null;
        addressLine1?: string | null;
        addressLine2?: string | null;
        city?: string | null;
        postalCode?: string | null;
        region?: string | null;
        country?: string | null;
        id?: string | null;
      }[]
    | null;
  marketingOptIn?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-identities".
 */
export interface CustomerIdentity {
  id: number;
  customer: number | Customer;
  provider: 'facebook' | 'google';
  providerUserId: string;
  providerKey: string;
  providerEmail?: string | null;
  providerEmailVerified?: boolean | null;
  rawProfile?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes".
 */
export interface PromoCode {
  id: number;
  code: string;
  name: string;
  status: 'active' | 'inactive';
  description?: string | null;
  application: {
    discountType: 'percent' | 'fixed';
    percentOff?: number | null;
    amountOff?: number | null;
    scope: 'cart' | 'brand' | 'category';
    brands?: (number | Brand)[] | null;
    categories?: (number | Category)[] | null;
    minimumSubtotal?: number | null;
    firstOrderOnly?: ('no' | 'yes') | null;
  };
  limits?: {
    maxUsesPerCustomer?: number | null;
    maxUsesTotal?: number | null;
  };
  schedule?: {
    startsAt?: string | null;
    endsAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  status: 'active' | 'converted' | 'abandoned';
  customer?: (number | null) | Customer;
  guestEmail?: string | null;
  items?:
    | {
        product: number | Product;
        quantity: number;
        unitPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  promoCode?: string | null;
  shipping?: {
    provider?: string | null;
    method?: string | null;
    label?: string | null;
    kind?: string | null;
    price?: number | null;
    pickupPoint?: {
      id?: string | null;
      externalId?: string | null;
      name?: string | null;
      type?: string | null;
      addressLine1?: string | null;
      postalCode?: string | null;
      city?: string | null;
      country?: string | null;
      size?: string | null;
      latitude?: number | null;
      longitude?: number | null;
      raw?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
  };
  payment?: {
    provider?: string | null;
    method?: string | null;
    status?: string | null;
  };
  totals?: {
    subtotal?: number | null;
    discount?: number | null;
    shipping?: number | null;
    grandTotal?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  status: 'pending' | 'awaiting-payment' | 'paid' | 'processing' | 'fulfilled' | 'completed' | 'cancelled' | 'refunded';
  orderNumber: string;
  customer?: (number | null) | Customer;
  guestEmail?: string | null;
  totals?: {
    subtotal?: number | null;
    discount?: number | null;
    shipping?: number | null;
    grandTotal?: number | null;
  };
  items: {
    product?: (number | null) | Product;
    title: string;
    productType?: string | null;
    brandName?: string | null;
    sku?: string | null;
    itemID?: string | null;
    quantity: number;
    unitPrice: number;
    lineTotal: number;
    discountTotal?: number | null;
    discountPercent?: number | null;
    finalLineTotal?: number | null;
    id?: string | null;
  }[];
  promotion?: {
    code?: string | null;
    name?: string | null;
    scope?: string | null;
    discountType?: string | null;
    discountValue?: number | null;
    discount?: number | null;
    eligibleSubtotal?: number | null;
    description?: string | null;
  };
  billingAddress: {
    firstName: string;
    lastName: string;
    isBusiness?: boolean | null;
    company?: string | null;
    taxId?: string | null;
    phone?: string | null;
    addressLine1: string;
    addressLine2?: string | null;
    city: string;
    postalCode: string;
    region?: string | null;
    country: string;
  };
  shippingAddress: {
    firstName: string;
    lastName: string;
    isBusiness?: boolean | null;
    company?: string | null;
    taxId?: string | null;
    phone?: string | null;
    addressLine1: string;
    addressLine2?: string | null;
    city: string;
    postalCode: string;
    region?: string | null;
    country: string;
  };
  payment?: {
    provider?: string | null;
    method?: string | null;
    label?: string | null;
    kind?: string | null;
    status?: string | null;
    externalID?: string | null;
    amount?: number | null;
    pickupPoint?: {
      id?: string | null;
      externalId?: string | null;
      name?: string | null;
      type?: string | null;
      addressLine1?: string | null;
      postalCode?: string | null;
      city?: string | null;
      country?: string | null;
      size?: string | null;
      latitude?: number | null;
      longitude?: number | null;
      raw?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    raw?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  shipping?: {
    provider?: string | null;
    method?: string | null;
    status?: string | null;
    price?: number | null;
    trackingCode?: string | null;
    pickupPoint?: {
      id?: string | null;
      externalId?: string | null;
      name?: string | null;
      type?: string | null;
      addressLine1?: string | null;
      postalCode?: string | null;
      city?: string | null;
      country?: string | null;
      size?: string | null;
      latitude?: number | null;
      longitude?: number | null;
      raw?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    raw?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  moralis?: {
    status?: string | null;
    customerType?: string | null;
    customerKey?: string | null;
    sifPar?: number | null;
    sifPj?: number | null;
    intBr?: number | null;
    brDok?: string | null;
    syncedAt?: string | null;
    failedAt?: string | null;
    lastError?: string | null;
    raw?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  notes?: string | null;
  statusTimeline?:
    | {
        status: string;
        at: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'products';
    value: number | Product;
  };
  slug?: string | null;
  brand?: string | null;
  categoryName?: string | null;
  priceLabel?: string | null;
  image?: string | null;
  searchText?: string | null;
  status?: string | null;
  catalogReviewStatus?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'listing-pages';
        value: number | ListingPage;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'customer-identities';
        value: number | CustomerIdentity;
      } | null)
    | ({
        relationTo: 'promo-codes';
        value: number | PromoCode;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  shortDescription?: T;
  story?: T;
  layout?:
    | T
    | {
        'brand-product-slider'?:
          | T
          | {
              section?:
                | T
                | {
                    title?: T;
                    browseLabel?: T;
                    browseType?: T;
                    browseOpenInNewTab?: T;
                    browseReference?: T;
                    browseAnchor?: T;
                    browseUrl?: T;
                  };
              visual?:
                | T
                | {
                    image?: T;
                    copy?: T;
                  };
              products?: T;
              id?: T;
              blockName?: T;
            };
        'brand-tile-grid'?:
          | T
          | {
              section?:
                | T
                | {
                    title?: T;
                    browseLabel?: T;
                    browseType?: T;
                    browseOpenInNewTab?: T;
                    browseReference?: T;
                    browseAnchor?: T;
                    browseUrl?: T;
                  };
              tiles?:
                | T
                | {
                    label?: T;
                    backgroundImage?: T;
                    cardType?: T;
                    cardOpenInNewTab?: T;
                    cardReference?: T;
                    cardAnchor?: T;
                    cardUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'brand-cta-banner'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              image?: T;
              actionLabel?: T;
              actionType?: T;
              actionOpenInNewTab?: T;
              actionReference?: T;
              actionAnchor?: T;
              actionUrl?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  publishedAt?: T;
  readingTime?: T;
  excerpt?: T;
  heroBadges?:
    | T
    | {
        primaryLabel?: T;
        stampLabel?: T;
      };
  image?: T;
  layout?:
    | T
    | {
        'callout-block'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        'content-block'?:
          | T
          | {
              title?: T;
              image?: T;
              caption?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  relatedBlogs?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        blogs?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  parent?: T;
  allowedProductTypes?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  title?: T;
  sections?:
    | T
    | {
        'content-section'?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-pages_select".
 */
export interface ListingPagesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  preappliedBrands?: T;
  preappliedCategories?: T;
  preappliedProductTypes?: T;
  visibleFilterKeys?: T;
  metaTitle?: T;
  metaDescription?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  categories?: T;
  badges?: T;
  heroImage?: T;
  notes?:
    | T
    | {
        label?: T;
        id?: T;
      };
  description?: T;
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  relatedProducts?: T;
  singleServeDetails?:
    | T
    | {
        format?: T;
        beverageType?: T;
        compatibleSystems?: T;
        packageUnits?: T;
        netContent?:
          | T
          | {
              generateDisplay?: T;
              amount?: T;
              unit?: T;
              display?: T;
            };
        flags?: T;
      };
  packagedCoffeeDetails?:
    | T
    | {
        format?: T;
        packageUnits?: T;
        netContent?:
          | T
          | {
              generateDisplay?: T;
              amount?: T;
              unit?: T;
              display?: T;
            };
        flags?: T;
      };
  equipmentDetails?:
    | T
    | {
        equipmentType?: T;
        compatibleSystems?: T;
        waterConnection?: T;
        burrType?: T;
        powerW?: T;
        ratedPowerW?: T;
        waterTankL?: T;
        groupCount?: T;
        burrDiameterMm?: T;
        ingredientCanistersCount?: T;
        directSelections?: T;
        hourCapacityL?: T;
      };
  accessoryDetails?:
    | T
    | {
        compatibleSystems?: T;
        packageUnits?: T;
        powerW?: T;
      };
  drinkMixDetails?:
    | T
    | {
        format?: T;
        beverageType?: T;
        physicalForm?: T;
        coffeeForm?: T;
        flavour?: T;
        packageUnits?: T;
        netContent?:
          | T
          | {
              generateDisplay?: T;
              amount?: T;
              unit?: T;
              display?: T;
            };
        flags?: T;
      };
  technicalConsumableDetails?:
    | T
    | {
        physicalForm?: T;
        compatibleSystems?: T;
        flags?: T;
      };
  teaMatchaDetails?:
    | T
    | {
        teaType?: T;
        flavorFamily?: T;
        packageUnits?: T;
        netContent?:
          | T
          | {
              generateDisplay?: T;
              amount?: T;
              unit?: T;
              display?: T;
            };
        flags?: T;
      };
  coldBeverageDetails?:
    | T
    | {
        beverageType?: T;
        flavour?: T;
        packageUnits?: T;
        netContent?:
          | T
          | {
              generateDisplay?: T;
              amount?: T;
              unit?: T;
              display?: T;
            };
      };
  confectioneryDetails?:
    | T
    | {
        productForm?: T;
        packageUnits?: T;
        netContent?:
          | T
          | {
              generateDisplay?: T;
              amount?: T;
              unit?: T;
              display?: T;
            };
        flags?: T;
      };
  moralis?:
    | T
    | {
        itemID?: T;
        sku?: T;
        price?: T;
        stockQuantity?: T;
        availabilityStatus?: T;
        isAvailable?: T;
        barcode?: T;
        unit?: T;
        taxRate?: T;
        lastSyncStatus?: T;
        lastSyncedAt?: T;
        lastSyncError?: T;
        rawOperationalData?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  status?: T;
  productType?: T;
  generateSlug?: T;
  slug?: T;
  catalogReviewStatus?: T;
  brand?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  billingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        isBusiness?: T;
        company?: T;
        taxId?: T;
        phone?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        postalCode?: T;
        region?: T;
        country?: T;
      };
  shippingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        isBusiness?: T;
        company?: T;
        taxId?: T;
        phone?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        postalCode?: T;
        region?: T;
        country?: T;
      };
  savedAddresses?:
    | T
    | {
        isDefault?: T;
        firstName?: T;
        lastName?: T;
        isBusiness?: T;
        company?: T;
        taxId?: T;
        phone?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        postalCode?: T;
        region?: T;
        country?: T;
        id?: T;
      };
  marketingOptIn?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-identities_select".
 */
export interface CustomerIdentitiesSelect<T extends boolean = true> {
  customer?: T;
  provider?: T;
  providerUserId?: T;
  providerKey?: T;
  providerEmail?: T;
  providerEmailVerified?: T;
  rawProfile?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes_select".
 */
export interface PromoCodesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  status?: T;
  description?: T;
  application?:
    | T
    | {
        discountType?: T;
        percentOff?: T;
        amountOff?: T;
        scope?: T;
        brands?: T;
        categories?: T;
        minimumSubtotal?: T;
        firstOrderOnly?: T;
      };
  limits?:
    | T
    | {
        maxUsesPerCustomer?: T;
        maxUsesTotal?: T;
      };
  schedule?:
    | T
    | {
        startsAt?: T;
        endsAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  status?: T;
  customer?: T;
  guestEmail?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        unitPrice?: T;
        id?: T;
      };
  promoCode?: T;
  shipping?:
    | T
    | {
        provider?: T;
        method?: T;
        label?: T;
        kind?: T;
        price?: T;
        pickupPoint?:
          | T
          | {
              id?: T;
              externalId?: T;
              name?: T;
              type?: T;
              addressLine1?: T;
              postalCode?: T;
              city?: T;
              country?: T;
              size?: T;
              latitude?: T;
              longitude?: T;
              raw?: T;
            };
      };
  payment?:
    | T
    | {
        provider?: T;
        method?: T;
        status?: T;
      };
  totals?:
    | T
    | {
        subtotal?: T;
        discount?: T;
        shipping?: T;
        grandTotal?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  status?: T;
  orderNumber?: T;
  customer?: T;
  guestEmail?: T;
  totals?:
    | T
    | {
        subtotal?: T;
        discount?: T;
        shipping?: T;
        grandTotal?: T;
      };
  items?:
    | T
    | {
        product?: T;
        title?: T;
        productType?: T;
        brandName?: T;
        sku?: T;
        itemID?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        discountTotal?: T;
        discountPercent?: T;
        finalLineTotal?: T;
        id?: T;
      };
  promotion?:
    | T
    | {
        code?: T;
        name?: T;
        scope?: T;
        discountType?: T;
        discountValue?: T;
        discount?: T;
        eligibleSubtotal?: T;
        description?: T;
      };
  billingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        isBusiness?: T;
        company?: T;
        taxId?: T;
        phone?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        postalCode?: T;
        region?: T;
        country?: T;
      };
  shippingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        isBusiness?: T;
        company?: T;
        taxId?: T;
        phone?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        postalCode?: T;
        region?: T;
        country?: T;
      };
  payment?:
    | T
    | {
        provider?: T;
        method?: T;
        label?: T;
        kind?: T;
        status?: T;
        externalID?: T;
        amount?: T;
        pickupPoint?:
          | T
          | {
              id?: T;
              externalId?: T;
              name?: T;
              type?: T;
              addressLine1?: T;
              postalCode?: T;
              city?: T;
              country?: T;
              size?: T;
              latitude?: T;
              longitude?: T;
              raw?: T;
            };
        raw?: T;
      };
  shipping?:
    | T
    | {
        provider?: T;
        method?: T;
        status?: T;
        price?: T;
        trackingCode?: T;
        pickupPoint?:
          | T
          | {
              id?: T;
              externalId?: T;
              name?: T;
              type?: T;
              addressLine1?: T;
              postalCode?: T;
              city?: T;
              country?: T;
              size?: T;
              latitude?: T;
              longitude?: T;
              raw?: T;
            };
        raw?: T;
      };
  moralis?:
    | T
    | {
        status?: T;
        customerType?: T;
        customerKey?: T;
        sifPar?: T;
        sifPj?: T;
        intBr?: T;
        brDok?: T;
        syncedAt?: T;
        failedAt?: T;
        lastError?: T;
        raw?: T;
      };
  notes?: T;
  statusTimeline?:
    | T
    | {
        status?: T;
        at?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  brand?: T;
  categoryName?: T;
  priceLabel?: T;
  image?: T;
  searchText?: T;
  status?: T;
  catalogReviewStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Main site URL used for search and sharing previews.
   */
  siteUrl: string;
  defaultTitle?: string | null;
  /**
   * Optional suffix added to generated page titles.
   */
  titleSuffix?: string | null;
  /**
   * Default search description used when a page has no custom summary.
   */
  defaultDescription?: string | null;
  defaultImage?: (number | null) | Media;
  /**
   * Optional robots rule, for example index,follow.
   */
  robots?: string | null;
  primaryEmail?: string | null;
  supportEmail?: string | null;
  phone?: string | null;
  address?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  gls: {
    availability?: ('enabled' | 'disabled') | null;
    price: number;
    label: string;
    disabledLabel: string;
    description?: string | null;
    apiBaseUrl?: string | null;
    serviceCode?: string | null;
    clientNumber?: string | null;
    /**
     * GLS API username used for shipment creation.
     */
    username?: string | null;
    /**
     * GLS API password or token used for shipment creation.
     */
    password?: string | null;
  };
  boxNow: {
    availability?: ('enabled' | 'disabled') | null;
    price: number;
    label: string;
    disabledLabel: string;
    description?: string | null;
    apiBaseUrl?: string | null;
    originId?: string | null;
    partnerId?: string | null;
    widgetScriptUrl?: string | null;
    /**
     * BOX NOW service value used in delivery request creation, for example next-day.
     */
    typeOfService?: string | null;
    /**
     * Payment mode sent to BOX NOW when creating the delivery request.
     */
    paymentMode?: ('prepaid' | 'cod') | null;
    /**
     * Required when BOX NOW origin is any-apm. Use 1 small, 2 medium, 3 large.
     */
    compartmentSize?: number | null;
    /**
     * BOX NOW API client ID used for authentication.
     */
    clientId?: string | null;
    /**
     * BOX NOW API client secret used for authentication.
     */
    clientSecret?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  announcementBar?: {
    mode?: ('hidden' | 'message') | null;
    text?: string | null;
  };
  primaryNavigation?:
    | {
        mode?: ('link' | 'mega-menu') | null;
        label: string;
        itemType: 'internal' | 'external';
        itemOpenInNewTab?: boolean | null;
        /**
         * Select an internal page.
         */
        itemReference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'legal-pages';
              value: number | LegalPage;
            } | null)
          | ({
              relationTo: 'listing-pages';
              value: number | ListingPage;
            } | null)
          | ({
              relationTo: 'products';
              value: number | Product;
            } | null)
          | ({
              relationTo: 'categories';
              value: number | Category;
            } | null);
        /**
         * Optional section ID, without the # symbol.
         */
        itemAnchor?: string | null;
        /**
         * Enter a full URL or relative path.
         */
        itemUrl?: string | null;
        megaMenu?: {
          layout?: ('classic' | 'brands-panel') | null;
          columns?:
            | {
                title: string;
                links?:
                  | {
                      label: string;
                      linkType: 'internal' | 'external';
                      linkOpenInNewTab?: boolean | null;
                      /**
                       * Select an internal page.
                       */
                      linkReference?:
                        | ({
                            relationTo: 'pages';
                            value: number | Page;
                          } | null)
                        | ({
                            relationTo: 'legal-pages';
                            value: number | LegalPage;
                          } | null)
                        | ({
                            relationTo: 'listing-pages';
                            value: number | ListingPage;
                          } | null)
                        | ({
                            relationTo: 'products';
                            value: number | Product;
                          } | null)
                        | ({
                            relationTo: 'categories';
                            value: number | Category;
                          } | null);
                      /**
                       * Optional section ID, without the # symbol.
                       */
                      linkAnchor?: string | null;
                      /**
                       * Enter a full URL or relative path.
                       */
                      linkUrl?: string | null;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
              }[]
            | null;
          featureCard?: {
            eyebrow?: string | null;
            title: string;
            image: number | Media;
            featureType: 'internal' | 'external';
            featureOpenInNewTab?: boolean | null;
            /**
             * Select an internal page.
             */
            featureReference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'legal-pages';
                  value: number | LegalPage;
                } | null)
              | ({
                  relationTo: 'listing-pages';
                  value: number | ListingPage;
                } | null)
              | ({
                  relationTo: 'products';
                  value: number | Product;
                } | null)
              | ({
                  relationTo: 'categories';
                  value: number | Category;
                } | null);
            /**
             * Optional section ID, without the # symbol.
             */
            featureAnchor?: string | null;
            /**
             * Enter a full URL or relative path.
             */
            featureUrl?: string | null;
          };
          brandPanel?: {
            title: string;
            brandLogos?:
              | {
                  name: string;
                  logo: number | Media;
                  logoType: 'internal' | 'external';
                  logoOpenInNewTab?: boolean | null;
                  /**
                   * Select an internal page.
                   */
                  logoReference?:
                    | ({
                        relationTo: 'pages';
                        value: number | Page;
                      } | null)
                    | ({
                        relationTo: 'legal-pages';
                        value: number | LegalPage;
                      } | null)
                    | ({
                        relationTo: 'listing-pages';
                        value: number | ListingPage;
                      } | null)
                    | ({
                        relationTo: 'products';
                        value: number | Product;
                      } | null)
                    | ({
                        relationTo: 'categories';
                        value: number | Category;
                      } | null);
                  /**
                   * Optional section ID, without the # symbol.
                   */
                  logoAnchor?: string | null;
                  /**
                   * Enter a full URL or relative path.
                   */
                  logoUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
          };
        };
        id?: string | null;
      }[]
    | null;
  mobileNavigation?:
    | {
        label: string;
        linkType: 'internal' | 'external';
        linkOpenInNewTab?: boolean | null;
        /**
         * Select an internal page.
         */
        linkReference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'legal-pages';
              value: number | LegalPage;
            } | null)
          | ({
              relationTo: 'listing-pages';
              value: number | ListingPage;
            } | null)
          | ({
              relationTo: 'products';
              value: number | Product;
            } | null)
          | ({
              relationTo: 'categories';
              value: number | Category;
            } | null);
        /**
         * Optional section ID, without the # symbol.
         */
        linkAnchor?: string | null;
        /**
         * Enter a full URL or relative path.
         */
        linkUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  topNavLinks?:
    | {
        label: string;
        linkType: 'internal' | 'external';
        linkOpenInNewTab?: boolean | null;
        /**
         * Select an internal page.
         */
        linkReference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'legal-pages';
              value: number | LegalPage;
            } | null)
          | ({
              relationTo: 'listing-pages';
              value: number | ListingPage;
            } | null)
          | ({
              relationTo: 'products';
              value: number | Product;
            } | null)
          | ({
              relationTo: 'categories';
              value: number | Category;
            } | null);
        /**
         * Optional section ID, without the # symbol.
         */
        linkAnchor?: string | null;
        /**
         * Enter a full URL or relative path.
         */
        linkUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  linkColumns?:
    | {
        links?:
          | {
              label: string;
              linkType: 'internal' | 'external';
              linkOpenInNewTab?: boolean | null;
              /**
               * Select an internal page.
               */
              linkReference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'legal-pages';
                    value: number | LegalPage;
                  } | null)
                | ({
                    relationTo: 'listing-pages';
                    value: number | ListingPage;
                  } | null)
                | ({
                    relationTo: 'products';
                    value: number | Product;
                  } | null)
                | ({
                    relationTo: 'categories';
                    value: number | Category;
                  } | null);
              /**
               * Optional section ID, without the # symbol.
               */
              linkAnchor?: string | null;
              /**
               * Enter a full URL or relative path.
               */
              linkUrl?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyright: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    backgroundImage: number | Media;
    title: string;
    description: string;
    primaryCtaLabel: string;
    primaryCtaType: 'internal' | 'external';
    primaryCtaOpenInNewTab?: boolean | null;
    /**
     * Select an internal page.
     */
    primaryCtaReference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'legal-pages';
          value: number | LegalPage;
        } | null)
      | ({
          relationTo: 'listing-pages';
          value: number | ListingPage;
        } | null)
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null)
      | ({
          relationTo: 'categories';
          value: number | Category;
        } | null);
    /**
     * Optional section ID, without the # symbol.
     */
    primaryCtaAnchor?: string | null;
    /**
     * Enter a full URL or relative path.
     */
    primaryCtaUrl?: string | null;
    highlights?:
      | {
          label: string;
          icon: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Flexible homepage sections shown below the hero.
   */
  layout?:
    | (
        | {
            section: {
              title: string;
              browseLabel: string;
              browseType: 'internal' | 'external';
              browseOpenInNewTab?: boolean | null;
              /**
               * Select an internal page.
               */
              browseReference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'legal-pages';
                    value: number | LegalPage;
                  } | null)
                | ({
                    relationTo: 'listing-pages';
                    value: number | ListingPage;
                  } | null)
                | ({
                    relationTo: 'products';
                    value: number | Product;
                  } | null)
                | ({
                    relationTo: 'categories';
                    value: number | Category;
                  } | null);
              /**
               * Optional section ID, without the # symbol.
               */
              browseAnchor?: string | null;
              /**
               * Enter a full URL or relative path.
               */
              browseUrl?: string | null;
            };
            /**
             * Select the products featured in this section.
             */
            products: (number | Product)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-products';
          }
        | {
            section: {
              /**
               * Intro heading for the category grid.
               */
              eyebrow?: string | null;
              title: string;
              browseLabel: string;
              browseType: 'internal' | 'external';
              browseOpenInNewTab?: boolean | null;
              /**
               * Select an internal page.
               */
              browseReference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'legal-pages';
                    value: number | LegalPage;
                  } | null)
                | ({
                    relationTo: 'listing-pages';
                    value: number | ListingPage;
                  } | null)
                | ({
                    relationTo: 'products';
                    value: number | Product;
                  } | null)
                | ({
                    relationTo: 'categories';
                    value: number | Category;
                  } | null);
              /**
               * Optional section ID, without the # symbol.
               */
              browseAnchor?: string | null;
              /**
               * Enter a full URL or relative path.
               */
              browseUrl?: string | null;
            };
            items?:
              | {
                  name: string;
                  backgroundImage: number | Media;
                  productImage: number | Media;
                  cardType: 'internal' | 'external';
                  cardOpenInNewTab?: boolean | null;
                  /**
                   * Select an internal page.
                   */
                  cardReference?:
                    | ({
                        relationTo: 'pages';
                        value: number | Page;
                      } | null)
                    | ({
                        relationTo: 'legal-pages';
                        value: number | LegalPage;
                      } | null)
                    | ({
                        relationTo: 'listing-pages';
                        value: number | ListingPage;
                      } | null)
                    | ({
                        relationTo: 'products';
                        value: number | Product;
                      } | null)
                    | ({
                        relationTo: 'categories';
                        value: number | Category;
                      } | null);
                  /**
                   * Optional section ID, without the # symbol.
                   */
                  cardAnchor?: string | null;
                  /**
                   * Enter a full URL or relative path.
                   */
                  cardUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'category-grid';
          }
        | {
            section: {
              /**
               * Heading shown above the category tiles directly below the hero.
               */
              title: string;
              browseLabel: string;
              browseType: 'internal' | 'external';
              browseOpenInNewTab?: boolean | null;
              /**
               * Select an internal page.
               */
              browseReference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'legal-pages';
                    value: number | LegalPage;
                  } | null)
                | ({
                    relationTo: 'listing-pages';
                    value: number | ListingPage;
                  } | null)
                | ({
                    relationTo: 'products';
                    value: number | Product;
                  } | null)
                | ({
                    relationTo: 'categories';
                    value: number | Category;
                  } | null);
              /**
               * Optional section ID, without the # symbol.
               */
              browseAnchor?: string | null;
              /**
               * Enter a full URL or relative path.
               */
              browseUrl?: string | null;
            };
            items?:
              | {
                  label: string;
                  backgroundImage: number | Media;
                  cardType: 'internal' | 'external';
                  cardOpenInNewTab?: boolean | null;
                  /**
                   * Select an internal page.
                   */
                  cardReference?:
                    | ({
                        relationTo: 'pages';
                        value: number | Page;
                      } | null)
                    | ({
                        relationTo: 'legal-pages';
                        value: number | LegalPage;
                      } | null)
                    | ({
                        relationTo: 'listing-pages';
                        value: number | ListingPage;
                      } | null)
                    | ({
                        relationTo: 'products';
                        value: number | Product;
                      } | null)
                    | ({
                        relationTo: 'categories';
                        value: number | Category;
                      } | null);
                  /**
                   * Optional section ID, without the # symbol.
                   */
                  cardAnchor?: string | null;
                  /**
                   * Enter a full URL or relative path.
                   */
                  cardUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'overlay-tile-grid';
          }
        | {
            section: {
              /**
               * Heading shown above the value cards.
               */
              eyebrow?: string | null;
              title: string;
            };
            items?:
              | {
                  title: string;
                  icon: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'icon-card-grid';
          }
        | {
            section: {
              /**
               * Heading shown above the partner logos.
               */
              eyebrow?: string | null;
              title: string;
            };
            items?:
              | {
                  title: string;
                  logo: number | Media;
                  logoType: 'internal' | 'external';
                  logoOpenInNewTab?: boolean | null;
                  /**
                   * Select an internal page.
                   */
                  logoReference?:
                    | ({
                        relationTo: 'pages';
                        value: number | Page;
                      } | null)
                    | ({
                        relationTo: 'legal-pages';
                        value: number | LegalPage;
                      } | null)
                    | ({
                        relationTo: 'listing-pages';
                        value: number | ListingPage;
                      } | null)
                    | ({
                        relationTo: 'products';
                        value: number | Product;
                      } | null)
                    | ({
                        relationTo: 'categories';
                        value: number | Category;
                      } | null);
                  /**
                   * Optional section ID, without the # symbol.
                   */
                  logoAnchor?: string | null;
                  /**
                   * Enter a full URL or relative path.
                   */
                  logoUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partners-grid';
          }
        | {
            section: {
              /**
               * Heading shown above the office feature.
               */
              eyebrow?: string | null;
              title: string;
            };
            featureCard: {
              backgroundImage: number | Media;
              eyebrow?: string | null;
              title: string;
              linkLabel: string;
              featureType: 'internal' | 'external';
              featureOpenInNewTab?: boolean | null;
              /**
               * Select an internal page.
               */
              featureReference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'legal-pages';
                    value: number | LegalPage;
                  } | null)
                | ({
                    relationTo: 'listing-pages';
                    value: number | ListingPage;
                  } | null)
                | ({
                    relationTo: 'products';
                    value: number | Product;
                  } | null)
                | ({
                    relationTo: 'categories';
                    value: number | Category;
                  } | null);
              /**
               * Optional section ID, without the # symbol.
               */
              featureAnchor?: string | null;
              /**
               * Enter a full URL or relative path.
               */
              featureUrl?: string | null;
            };
            /**
             * Select the products shown alongside the office feature.
             */
            products: (number | Product)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'office-shop';
          }
        | {
            section: {
              /**
               * Heading shown above the order steps.
               */
              eyebrow?: string | null;
              title: string;
            };
            steps?:
              | {
                  title: string;
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'how-to-order';
          }
        | {
            stories?:
              | {
                  eyebrow?: string | null;
                  title: string;
                  description: string;
                  image: number | Media;
                  ctaMode?: ('hidden' | 'enabled') | null;
                  ctaLabel?: string | null;
                  ctaType?: ('internal' | 'external') | null;
                  ctaOpenInNewTab?: boolean | null;
                  /**
                   * Select an internal page.
                   */
                  ctaReference?:
                    | ({
                        relationTo: 'pages';
                        value: number | Page;
                      } | null)
                    | ({
                        relationTo: 'legal-pages';
                        value: number | LegalPage;
                      } | null)
                    | ({
                        relationTo: 'listing-pages';
                        value: number | ListingPage;
                      } | null)
                    | ({
                        relationTo: 'products';
                        value: number | Product;
                      } | null)
                    | ({
                        relationTo: 'categories';
                        value: number | Category;
                      } | null);
                  /**
                   * Optional section ID, without the # symbol.
                   */
                  ctaAnchor?: string | null;
                  /**
                   * Enter a full URL or relative path.
                   */
                  ctaUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'story-pair';
          }
        | {
            eyebrow?: string | null;
            title: string;
            emailPlaceholder: string;
            submitLabel: string;
            disclaimerText: string;
            disclaimerLinkLabel: string;
            disclaimerType: 'internal' | 'external';
            disclaimerOpenInNewTab?: boolean | null;
            /**
             * Select an internal page.
             */
            disclaimerReference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'legal-pages';
                  value: number | LegalPage;
                } | null)
              | ({
                  relationTo: 'listing-pages';
                  value: number | ListingPage;
                } | null)
              | ({
                  relationTo: 'products';
                  value: number | Product;
                } | null)
              | ({
                  relationTo: 'categories';
                  value: number | Category;
                } | null);
            /**
             * Optional section ID, without the # symbol.
             */
            disclaimerAnchor?: string | null;
            /**
             * Enter a full URL or relative path.
             */
            disclaimerUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter-signup';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  intro: {
    /**
     * Heading shown at the top of the blogs page.
     */
    eyebrow?: string | null;
    title: string;
  };
  featuredBlogs?:
    | {
        blog: number | Blog;
        ctaLabel: string;
        id?: string | null;
      }[]
    | null;
  latestBlogs: {
    /**
     * Heading shown above the latest blogs grid.
     */
    eyebrow?: string | null;
    title: string;
    description: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteUrl?: T;
  defaultTitle?: T;
  titleSuffix?: T;
  defaultDescription?: T;
  defaultImage?: T;
  robots?: T;
  primaryEmail?: T;
  supportEmail?: T;
  phone?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  gls?:
    | T
    | {
        availability?: T;
        price?: T;
        label?: T;
        disabledLabel?: T;
        description?: T;
        apiBaseUrl?: T;
        serviceCode?: T;
        clientNumber?: T;
        username?: T;
        password?: T;
      };
  boxNow?:
    | T
    | {
        availability?: T;
        price?: T;
        label?: T;
        disabledLabel?: T;
        description?: T;
        apiBaseUrl?: T;
        originId?: T;
        partnerId?: T;
        widgetScriptUrl?: T;
        typeOfService?: T;
        paymentMode?: T;
        compartmentSize?: T;
        clientId?: T;
        clientSecret?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  announcementBar?:
    | T
    | {
        mode?: T;
        text?: T;
      };
  primaryNavigation?:
    | T
    | {
        mode?: T;
        label?: T;
        itemType?: T;
        itemOpenInNewTab?: T;
        itemReference?: T;
        itemAnchor?: T;
        itemUrl?: T;
        megaMenu?:
          | T
          | {
              layout?: T;
              columns?:
                | T
                | {
                    title?: T;
                    links?:
                      | T
                      | {
                          label?: T;
                          linkType?: T;
                          linkOpenInNewTab?: T;
                          linkReference?: T;
                          linkAnchor?: T;
                          linkUrl?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              featureCard?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    image?: T;
                    featureType?: T;
                    featureOpenInNewTab?: T;
                    featureReference?: T;
                    featureAnchor?: T;
                    featureUrl?: T;
                  };
              brandPanel?:
                | T
                | {
                    title?: T;
                    brandLogos?:
                      | T
                      | {
                          name?: T;
                          logo?: T;
                          logoType?: T;
                          logoOpenInNewTab?: T;
                          logoReference?: T;
                          logoAnchor?: T;
                          logoUrl?: T;
                          id?: T;
                        };
                  };
            };
        id?: T;
      };
  mobileNavigation?:
    | T
    | {
        label?: T;
        linkType?: T;
        linkOpenInNewTab?: T;
        linkReference?: T;
        linkAnchor?: T;
        linkUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  topNavLinks?:
    | T
    | {
        label?: T;
        linkType?: T;
        linkOpenInNewTab?: T;
        linkReference?: T;
        linkAnchor?: T;
        linkUrl?: T;
        id?: T;
      };
  linkColumns?:
    | T
    | {
        links?:
          | T
          | {
              label?: T;
              linkType?: T;
              linkOpenInNewTab?: T;
              linkReference?: T;
              linkAnchor?: T;
              linkUrl?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundImage?: T;
        title?: T;
        description?: T;
        primaryCtaLabel?: T;
        primaryCtaType?: T;
        primaryCtaOpenInNewTab?: T;
        primaryCtaReference?: T;
        primaryCtaAnchor?: T;
        primaryCtaUrl?: T;
        highlights?:
          | T
          | {
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  layout?:
    | T
    | {
        'featured-products'?:
          | T
          | {
              section?:
                | T
                | {
                    title?: T;
                    browseLabel?: T;
                    browseType?: T;
                    browseOpenInNewTab?: T;
                    browseReference?: T;
                    browseAnchor?: T;
                    browseUrl?: T;
                  };
              products?: T;
              id?: T;
              blockName?: T;
            };
        'category-grid'?:
          | T
          | {
              section?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    browseLabel?: T;
                    browseType?: T;
                    browseOpenInNewTab?: T;
                    browseReference?: T;
                    browseAnchor?: T;
                    browseUrl?: T;
                  };
              items?:
                | T
                | {
                    name?: T;
                    backgroundImage?: T;
                    productImage?: T;
                    cardType?: T;
                    cardOpenInNewTab?: T;
                    cardReference?: T;
                    cardAnchor?: T;
                    cardUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'overlay-tile-grid'?:
          | T
          | {
              section?:
                | T
                | {
                    title?: T;
                    browseLabel?: T;
                    browseType?: T;
                    browseOpenInNewTab?: T;
                    browseReference?: T;
                    browseAnchor?: T;
                    browseUrl?: T;
                  };
              items?:
                | T
                | {
                    label?: T;
                    backgroundImage?: T;
                    cardType?: T;
                    cardOpenInNewTab?: T;
                    cardReference?: T;
                    cardAnchor?: T;
                    cardUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'icon-card-grid'?:
          | T
          | {
              section?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                  };
              items?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'partners-grid'?:
          | T
          | {
              section?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                  };
              items?:
                | T
                | {
                    title?: T;
                    logo?: T;
                    logoType?: T;
                    logoOpenInNewTab?: T;
                    logoReference?: T;
                    logoAnchor?: T;
                    logoUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'office-shop'?:
          | T
          | {
              section?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                  };
              featureCard?:
                | T
                | {
                    backgroundImage?: T;
                    eyebrow?: T;
                    title?: T;
                    linkLabel?: T;
                    featureType?: T;
                    featureOpenInNewTab?: T;
                    featureReference?: T;
                    featureAnchor?: T;
                    featureUrl?: T;
                  };
              products?: T;
              id?: T;
              blockName?: T;
            };
        'how-to-order'?:
          | T
          | {
              section?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                  };
              steps?:
                | T
                | {
                    title?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'story-pair'?:
          | T
          | {
              stories?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    description?: T;
                    image?: T;
                    ctaMode?: T;
                    ctaLabel?: T;
                    ctaType?: T;
                    ctaOpenInNewTab?: T;
                    ctaReference?: T;
                    ctaAnchor?: T;
                    ctaUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'newsletter-signup'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              emailPlaceholder?: T;
              submitLabel?: T;
              disclaimerText?: T;
              disclaimerLinkLabel?: T;
              disclaimerType?: T;
              disclaimerOpenInNewTab?: T;
              disclaimerReference?: T;
              disclaimerAnchor?: T;
              disclaimerUrl?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  featuredBlogs?:
    | T
    | {
        blog?: T;
        ctaLabel?: T;
        id?: T;
      };
  latestBlogs?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}